### ISSUE TITLE
I2C support? 

### ISSUE THREAD

**Issue by michaelboeding** [Kampi/ESP32-RAK3172#22]
Is there support for I2C in this or just UART? @Kampi

**Comment by Kampi** [comment]
There is no support for the other peripherals.

**Comment by Kampi** [comment]
> Hey @Kampi - yes I think I was wrong earlier. It looks like the only way to communicate with the module is over UART? So I2C wouldn't even be an option I think.

Yes. Only UART is supported as protocol interface. You can use I2C when you run your custom firmware.
